# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - type: github_release
    repo_owner: prometheus-community
    repo_name: pgbouncer_exporter
    description: Prometheus exporter for PgBouncer
    asset: pgbouncer_exporter-{{trimV .Version}}.{{.OS}}-{{.Arch}}.tar.gz
    checksum:
      type: github_release
      asset: sha256sums.txt
      algorithm: sha256
    files:
      - name: pgbouncer_exporter
        src: pgbouncer_exporter-{{trimV .Version}}.{{.OS}}-{{.Arch}}/pgbouncer_exporter
