#!/usr/bin/env bash
# Regenerate the monolithic root registry.yaml from every pkgs/**/registry.yaml.
# aqua registry files have no `import`, so the root must inline every package.
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p pkgs
{
  echo '# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json'
  echo '# GENERATED by scripts/build-registry.sh — do not edit by hand.'
  echo 'packages:'
  # For each package source, emit only its list entries (everything after its own `packages:` line).
  find pkgs -name registry.yaml | sort | while read -r f; do
    awk 'seen{print} /^packages:/{seen=1}' "$f"
  done
} > registry.yaml
