#!/usr/bin/env bash
# Regenerate the monolithic root registry.yaml from every pkgs/**/registry.yaml.
# aqua registry files have no `import`, so the root must inline every package.
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p pkgs
{
  echo '# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json'
  echo '# GENERATED by scripts/build-registry.sh — do not edit by hand.'
  echo 'packages:'
  # For each package source, emit only its list entries (everything after its own `packages:` line).
  # LC_ALL=C: the order must not depend on the caller's locale. A case-insensitive
  # collation (fr_FR.UTF-8, en_US.UTF-8) moved Infisical/ and StackExchange/ and
  # reordered the whole monolith on every regeneration.
  find pkgs -name registry.yaml | LC_ALL=C sort | while read -r f; do
    awk 'seen{print} /^packages:/{seen=1}' "$f"
  done
} > registry.yaml
